apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-etudiant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion-etudiant
  template:
    metadata:
      labels:
        app: gestion-etudiant
    spec:
      containers:
      - name: app
        image: gestion-etudiant:latest
        ports:
        - containerPort: 9000
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          value: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-etudiant
spec:
  selector:
    app: gestion-etudiant
  ports:
  - port: 80
    targetPort: 9000
  type: LoadBalancer
