---
# =============================================================================
# Kubernetes Namespace
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: gestion-etudiant
  labels:
    name: gestion-etudiant
    environment: production
